/**
 * The Slate client.
 */

import { applyImmutableDiffOperations } from "./utils/immutableDiffToAutomerge"
import { applySlateOperations } from "./utils/slateOpsToAutomerge"
import { convertAutomergeToSlateOps } from "./utils/convertAutomergeToSlateOps"
import { Editor } from 'slate-react'
import { Value } from 'slate'
import Automerge from 'automerge'
import Immutable from "immutable";
import React from 'react'
import EditList from 'slate-edit-list'
import automergeJsonToSlate from "./utils/automergeJsonToSlate"


/**
 * @function uselessFunction
 * @desc This is a completely useless function but for some odd reason, the
 *     sync-ing fails to work if I remove this function... I have absolutely no
 *     idea why...
 */
const uselessFunction = (a, b) => {
  return Immutable.is(a, b) ? Immutable.List() : Immutable.List([""]);
};


const plugin = EditList();
const plugins = [
  plugin
]

function renderNode(props: *) {
    const { node, attributes, children, editor } = props;
    const isCurrentItem = plugin.utils
        .getItemsAtRange(editor.value)
        .contains(node);

    switch (node.type) {
        case 'ul_list':
            return <ul {...attributes}>{children}</ul>;
        case 'ol_list':
            return <ol {...attributes}>{children}</ol>;

        case 'list_item':
            return (
                <li
                    className={isCurrentItem ? 'current-item' : ''}
                    title={isCurrentItem ? 'Current Item' : ''}
                    {...props.attributes}
                >
                    {props.children}
                </li>
            );

        case 'paragraph':
            return <div {...attributes}>{children}</div>;
        case 'heading':
            return <h1 {...attributes}>{children}</h1>;
        default:
            return <div {...attributes}>{children}</div>;
    }
}


export class Client extends React.Component {

    constructor(props) {
      super(props)

      this.onChange = this.onChange.bind(this)
      this.doc = Automerge.load(this.props.savedAutomergeDoc)
      this.pathMap = null;

      this.docSet = new Automerge.DocSet()
      const clientNumber = this.props.clientNumber
      this.connection = new Automerge.Connection(
        this.docSet,
        (msg) => {
          this.props.broadcast(clientNumber, msg)
        }
      );

      const initialValue = automergeJsonToSlate({
        "document": {...this.doc.note}
      })
      const initialSlateValue = Value.fromJSON(initialValue);

      this.state = {
        value: initialSlateValue,
        online: this.props.online,
        docOfflineHistory: Immutable.List(),
      }
    }

    componentDidMount = () => {
      this.connection.open()
      this.docSet.setDoc(this.props.docId, this.doc)
    }

    componentWillReceiveProps = (nextProps) => {
      if (this.props.online !== nextProps.online) {
        this.setState({ online: nextProps.online })
      }
    }

    /***************************************
     * UPDATE CLIENT FROM REMOTE OPERATION *
     ***************************************/
    /**
     * @function updateWithRemoteChanges
     * @desc Update the Automerge document with changes from another client
     * @param {Array} msg - A message created by Automerge.Connection
     */
    updateWithRemoteChanges = ( msg ) => {
      const currentDoc = this.docSet.getDoc(this.props.docId)
      const docNew = this.connection.receiveMsg(msg)
      const opSetDiff = Automerge.diff(currentDoc, docNew)
      if (opSetDiff.length !== 0) {
        this.updateWithAutomergeOperations(this.state.value, opSetDiff);
      }
    }

    /**
     * @function updateWithAutomergeOperations
     * @desc Update the client with a list of Automerge operations. If an error
     *     occurs, reload the document using Automerge as the ground truth.
     * @param {Value} currentValue - The current (or latest) Slate Value
     * @param {Array} opSetDiff - The Automerge operations generated by Automerge.diff
     */
    updateWithAutomergeOperations = (currentValue, opSetDiff) => {
      // Convert the changes from the Automerge document to Slate operations
      let newValue;
      try {
        const slateOps = convertAutomergeToSlateOps(opSetDiff, currentValue)
        const change = currentValue.change()

        // Apply the operation
        try {
          change.applyOperations(slateOps)
        } catch (err) { }

        newValue = change.value
      } catch (e) {
        // If an error occurs, release the Slate Value based on the Automerge
        // document, which is the ground truth.
        console.error(e)
        const doc = this.docSet.getDoc(this.props.docId)
        const newJson = automergeJsonToSlate({
          "document": {...doc.note}
        })
        newValue = Value.fromJSON(newJson)
      }
      this.setState({ value: newValue })
    }

    /**
     * TOGGLE ONLINE
     */
    toggleOnline = () => {
      this.setState({online: !this.state.online});
    }

    /**************************************
     * UPDATE CLIENT FROM LOCAL OPERATION *
     **************************************/
    onChange = ({ operations, value }) => {

      const differences = uselessFunction(this.state.value.document, value.document);

      this.setState({ value: value })

      // Run only if the Slate value has changed.
      // For some reason, when I don't have this nearly trivial condition,
      // the syncing doesn't work as I expect. I still need to investigate why.
      if (differences.size) {

        const currentDoc = this.docSet.getDoc(this.props.docId)
        const docNew = Automerge.change(currentDoc, `Client ${this.props.clientNumber}`, doc => {
          // Approach 1 which uses the difference between two Automerge documents
          // to calculate the operations.
          // applyImmutableDiffOperations(doc, differences)

          // Approach 2 which directly uses the Slate operations to modify the
          // Automerge document.
          applySlateOperations(doc, operations)
        })

        this.docSet.setDoc(this.props.docId, docNew);
      }
    }

    /*****************
     * RENDER CLIENT *
     *****************/
    render = () => {
        return (
            <div>
              <span><u>Client: {this.props.clientNumber}</u></span>
              {/*<button onClick={this.toggleOnline}>Online</button>*/}
              <Editor
                  key={this.props.clientNumber}
                  ref={(e) => {this.editor = e}}
                  value={this.state.value}
                  onChange={this.onChange}
                  renderNode={renderNode}
                  plugins={plugins}
              />
            </div>
        )
    }
}
